learning_template/basic_app/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views


#template tagging
app_name = 'basic_app'

urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
]

learning_template/learning_template/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views



urlpatterns = [


    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls'))

]

learning_template/basic_app/models.py
from django.db import models

# Create your models here.

learning_template/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_template/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script> -->

  </head>
  <body>
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="#">BRAND</a></li>
          <li><a class="navbar-link" href="#">Admin</a></li>
          <li><a class="navbar-link" href="#">Other</a></li>
        </ul>
      </div>
    </nav> -->


‭<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <!-- <li class="nav-item active"> -->
      <li class="nav-item">
        <!-- <a class="nav-link" href="#">BRAND <span class="sr-only">(current)</span></a> -->
        <a class="nav-link" href="{% url 'index' %}">BRAND</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
      </li>

    </ul>
  </div>
</nav>


    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you -->
      {% endblock %}
    </div>
  </body>
</html>

learning_template/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>Welcome to index</h1>
    <h1>{{ text|cut:'hello' }}</h1>
    <h1>{{ number|add:"123" }}</h1>

{% endblock %}

learning_template/templates/basic_app/other.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>Welcome to other</h1>
    <h2>This is an example of template inheritance!</h2>
{% endblock %}

learning_template/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>Welcome to ralative url template</h1>
    <a href="{% url 'basic_app:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">Link to admin page</a>
    <a href="{% url 'basic_app:index' %}">Link to index page</a>
{% endblock %}